services:
  api:
    container_name: authapi
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  db:
    container_name: authapiservice
    image: postgres:18
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - data:/data/db
      - ./src/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  data: {}

