include:
  - docker-compose.collector.yaml
  - docker-compose.grafana.yaml
  - docker-compose.api.yaml
services:
  telemetrygen:
    image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.148.0
    profiles:
      - "scripts"
    command: --otlp-endpoint "collector"
  trafficgen:
    build:
      context: ./gen-traffic
      dockerfile: Dockerfile
    profiles:
      - "scripts"
    environment:
      USER_COUNT: ${USER_COUNT:-100}
      AUTH_URL: http://auth-service:8000
      PROFILE_URL: http://profile-service:8080
