include:
  - docker-compose.tempo.yaml
  - docker-compose.loki.yaml
  - docker-compose.prometheus.yaml
services:
  collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.147.0
    ports:
      - 4317:4317
      - 4318:4318
      - 55679:55679
      - 13133:13133
      - 8888:8888
    volumes:
      - ./otel-config.yaml:/etc/otelcol/config.yaml
    command: --config=/etc/otelcol/config.yaml
    depends_on:
      - tempo
      - loki
      - prometheus
