include:
  - docker-compose.tempo.yaml
  - docker-compose.loki.yaml
  - docker-compose.prometheus.yaml
services:
  collector:
    image: docker.io/otel/opentelemetry-collector:latest
    ports:
      - 4317:4317
      - 4318:4318
      - 55679:55679
      - 1777:1777
      - 13133:13133
    volumes:
      - ./otel-config.yaml:/etc/otelcol/config.yaml
    depends_on:
      - tempo
      - loki
      - prometheus
